#!/usr/bin/env bash
# Generated by orca-ager — do not freehand. Re-emit after graph changes.
set -euo pipefail
OBJECTIVE="${1:-start new feature: <description>}"
command -v orca >/dev/null || { echo "orca CLI not on PATH"; exit 1; }
command -v jq >/dev/null || { echo "jq is required"; exit 1; }

RUN_ID=$(orca orchestration run-create --objective "$OBJECTIVE" --json | jq -r .id)
echo "run $RUN_ID"

# --- Draft plan (plan-draft) ---
TASK_CLAUDE_PLAN_DRAFTER=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Claude-Plan-Drafter" --json | jq -r .id)
orca orchestration worker-start --task "$TASK_CLAUDE_PLAN_DRAFTER" --worktree current --name Claude-Plan-Drafter --agent claude --json
orca terminal send --text "$(cat agents/Claude-Plan-Drafter/SYSTEM.md)" --enter --json >/dev/null || true
orca orchestration check --wait --types worker_done --timeout-ms 900000 --json

# --- Parallel plan review (plan-review) ---
TASK_GROK_PLAN_REVIEWER=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Grok-Plan-Reviewer" --json | jq -r .id)
orca orchestration worker-start --task "$TASK_GROK_PLAN_REVIEWER" --worktree current --name Grok-Plan-Reviewer --agent grok --json
orca terminal send --text "$(cat agents/Grok-Plan-Reviewer/SYSTEM.md)" --enter --json >/dev/null || true
TASK_CODEX_PLAN_REVIEWER=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Codex-Plan-Reviewer" --json | jq -r .id)
orca orchestration worker-start --task "$TASK_CODEX_PLAN_REVIEWER" --worktree current --name Codex-Plan-Reviewer --agent codex --json
orca terminal send --text "$(cat agents/Codex-Plan-Reviewer/SYSTEM.md)" --enter --json >/dev/null || true
orca orchestration check --wait --types worker_done,escalation,question --timeout-ms 900000 --json

# --- Refine plan (plan-refine) ---
TASK_CLAUDE_PLAN_REFINER=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Claude-Plan-Refiner" --json | jq -r .id)
orca orchestration worker-start --task "$TASK_CLAUDE_PLAN_REFINER" --worktree current --name Claude-Plan-Refiner --agent claude --json
orca terminal send --text "$(cat agents/Claude-Plan-Refiner/SYSTEM.md)" --enter --json >/dev/null || true
orca orchestration check --wait --types worker_done --timeout-ms 900000 --json

# --- Parallel implementers (implement) ---
TASK_CLAUDE_IMPLEMENTER=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Claude-Implementer" --json | jq -r .id)
orca worktree create --name wt-claude --agent claude --json >/dev/null
orca orchestration worker-start --task "$TASK_CLAUDE_IMPLEMENTER" --worktree new-top-level --name Claude-Implementer --agent claude --json
orca terminal send --text "$(cat agents/Claude-Implementer/SYSTEM.md)" --enter --json >/dev/null || true
TASK_GROK_IMPLEMENTER=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Grok-Implementer" --json | jq -r .id)
orca worktree create --name wt-grok --agent grok --json >/dev/null
orca orchestration worker-start --task "$TASK_GROK_IMPLEMENTER" --worktree new-top-level --name Grok-Implementer --agent grok --json
orca terminal send --text "$(cat agents/Grok-Implementer/SYSTEM.md)" --enter --json >/dev/null || true
TASK_CODEX_IMPLEMENTER=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Codex-Implementer" --json | jq -r .id)
orca worktree create --name wt-codex --agent codex --json >/dev/null
orca orchestration worker-start --task "$TASK_CODEX_IMPLEMENTER" --worktree new-top-level --name Codex-Implementer --agent codex --json
orca terminal send --text "$(cat agents/Codex-Implementer/SYSTEM.md)" --enter --json >/dev/null || true
orca orchestration check --wait --types worker_done,escalation,question --timeout-ms 900000 --json

# --- Cross-critique (judge) ---
TASK_CLAUDE_JUDGE=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Claude-Judge" --json | jq -r .id)
orca worktree create --name wt-judge-claude --agent claude --json >/dev/null
orca orchestration worker-start --task "$TASK_CLAUDE_JUDGE" --worktree new-top-level --name Claude-Judge --agent claude --json
orca terminal send --text "$(cat agents/Claude-Judge/SYSTEM.md)" --enter --json >/dev/null || true
TASK_GROK_JUDGE=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Grok-Judge" --json | jq -r .id)
orca worktree create --name wt-judge-grok --agent grok --json >/dev/null
orca orchestration worker-start --task "$TASK_GROK_JUDGE" --worktree new-top-level --name Grok-Judge --agent grok --json
orca terminal send --text "$(cat agents/Grok-Judge/SYSTEM.md)" --enter --json >/dev/null || true
TASK_CODEX_JUDGE=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Codex-Judge" --json | jq -r .id)
orca worktree create --name wt-judge-codex --agent codex --json >/dev/null
orca orchestration worker-start --task "$TASK_CODEX_JUDGE" --worktree new-top-level --name Codex-Judge --agent codex --json
orca terminal send --text "$(cat agents/Codex-Judge/SYSTEM.md)" --enter --json >/dev/null || true
orca orchestration check --wait --types worker_done,escalation,question --timeout-ms 900000 --json

# --- Mediate and steal (mediate) ---
TASK_GROK_MEDIATOR=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Grok-Mediator" --json | jq -r .id)
orca orchestration worker-start --task "$TASK_GROK_MEDIATOR" --worktree current --name Grok-Mediator --agent grok --json
orca terminal send --text "$(cat agents/Grok-Mediator/SYSTEM.md)" --enter --json >/dev/null || true
orca orchestration check --wait --types worker_done --timeout-ms 900000 --json

# --- Final spec review (spec-review) ---
TASK_FINAL_SPEC_REVIEWER=$(orca orchestration task-create --spec "$OBJECTIVE" --task-title "Final-Spec-Reviewer" --json | jq -r .id)
orca orchestration worker-start --task "$TASK_FINAL_SPEC_REVIEWER" --worktree current --name Final-Spec-Reviewer --agent claude --json
orca terminal send --text "$(cat agents/Final-Spec-Reviewer/SYSTEM.md)" --enter --json >/dev/null || true
orca orchestration check --wait --types worker_done --timeout-ms 900000 --json

# HumanGate: merge-gate
orca orchestration gate-create --task "$RUN_ID" --question "Create the PR from the winning worktree and merge to main?" --options '["merge", "hold"]' --json
echo "orca-ager run complete: $RUN_ID"
