#!/usr/bin/env bash
# Generated by orca-ager. Bootstrap + orchestration DAG. Re-emit after graph changes.
# orca-cli        → named worktrees, terminals, handoffs (never raw git worktree)
# orchestration   → run-create, task-create, worker-start --name, check --wait, gate-create
set -euo pipefail
OBJECTIVE="${1:-start new feature: <description>}"

resolve_orca_bin() {
  if [ -n "${ORCA_CLI_COMMAND:-}" ]; then
    printf '%s\n' "$ORCA_CLI_COMMAND"
    return
  fi
  if [ -n "${ORCA_DEV_REPO_ROOT:-}" ]; then
    printf '%s\n' "orca-dev"
    return
  fi
  case "$(uname -s)" in
    Linux)
      if [ -n "${ORCA_SESSION:-}" ] || [ -n "${ORCA_MANAGED:-}" ]; then
        printf '%s\n' "orca"
      else
        # Never bare `orca` on Linux outside an Orca terminal (GNOME screen reader).
        printf '%s\n' "orca-ide"
      fi
      ;;
    *)
      printf '%s\n' "orca"
      ;;
  esac
}

ORCA_BIN=$(resolve_orca_bin)
command -v "$ORCA_BIN" >/dev/null || { echo "Orca CLI not on PATH (resolved: $ORCA_BIN). Install Orca ADE or set ORCA_CLI_COMMAND."; exit 1; }
command -v jq >/dev/null || { echo "jq is required"; exit 1; }

# Confirm the ADE is up (from orca-cli / orchestration skill stubs).
"$ORCA_BIN" status --json >/dev/null 2>&1 || "$ORCA_BIN" open --json >/dev/null

# Peer skills. Stubs are discovery-only; load the live guide next.
"$ORCA_BIN" skills install --skill orca-cli --skill orchestration >/dev/null 2>&1 || true
"$ORCA_BIN" skills get orca-cli >/dev/null
"$ORCA_BIN" skills get orchestration --full >/dev/null

RUN_ID=$("$ORCA_BIN" orchestration run-create --objective "$OBJECTIVE" --json | jq -r .id)
echo "run $RUN_ID"

# --- Draft plan (plan-draft) via orchestration ---
TASK_CLAUDE_PLAN_DRAFTER=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Claude-Plan-Drafter" --json | jq -r .id)
"$ORCA_BIN" orchestration worker-start --task "$TASK_CLAUDE_PLAN_DRAFTER" --worktree current --name Claude-Plan-Drafter --agent claude --json
"$ORCA_BIN" terminal send --text "$(cat agents/Claude-Plan-Drafter/SYSTEM.md)" --enter --json >/dev/null || true
"$ORCA_BIN" orchestration check --wait --types worker_done --timeout-ms 900000 --json

# --- Parallel plan review (plan-review) via orchestration ---
TASK_GROK_PLAN_REVIEWER=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Grok-Plan-Reviewer" --json | jq -r .id)
"$ORCA_BIN" orchestration worker-start --task "$TASK_GROK_PLAN_REVIEWER" --worktree current --name Grok-Plan-Reviewer --agent grok --json
"$ORCA_BIN" terminal send --text "$(cat agents/Grok-Plan-Reviewer/SYSTEM.md)" --enter --json >/dev/null || true
TASK_CODEX_PLAN_REVIEWER=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Codex-Plan-Reviewer" --json | jq -r .id)
"$ORCA_BIN" orchestration worker-start --task "$TASK_CODEX_PLAN_REVIEWER" --worktree current --name Codex-Plan-Reviewer --agent codex --json
"$ORCA_BIN" terminal send --text "$(cat agents/Codex-Plan-Reviewer/SYSTEM.md)" --enter --json >/dev/null || true
"$ORCA_BIN" orchestration check --wait --types worker_done,escalation,question --timeout-ms 900000 --json

# --- Refine plan (plan-refine) via orchestration ---
TASK_CLAUDE_PLAN_REFINER=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Claude-Plan-Refiner" --json | jq -r .id)
"$ORCA_BIN" orchestration worker-start --task "$TASK_CLAUDE_PLAN_REFINER" --worktree current --name Claude-Plan-Refiner --agent claude --json
"$ORCA_BIN" terminal send --text "$(cat agents/Claude-Plan-Refiner/SYSTEM.md)" --enter --json >/dev/null || true
"$ORCA_BIN" orchestration check --wait --types worker_done --timeout-ms 900000 --json

# --- Parallel implementers (implement) via orca-cli worktrees + orchestration workers ---
TASK_CLAUDE_IMPLEMENTER=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Claude-Implementer" --json | jq -r .id)
"$ORCA_BIN" worktree create --name wt-claude --agent claude --json >/dev/null
"$ORCA_BIN" orchestration worker-start --task "$TASK_CLAUDE_IMPLEMENTER" --worktree wt-claude --name Claude-Implementer --agent claude --json
"$ORCA_BIN" terminal send --text "$(cat agents/Claude-Implementer/SYSTEM.md)" --enter --json >/dev/null || true
TASK_GROK_IMPLEMENTER=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Grok-Implementer" --json | jq -r .id)
"$ORCA_BIN" worktree create --name wt-grok --agent grok --json >/dev/null
"$ORCA_BIN" orchestration worker-start --task "$TASK_GROK_IMPLEMENTER" --worktree wt-grok --name Grok-Implementer --agent grok --json
"$ORCA_BIN" terminal send --text "$(cat agents/Grok-Implementer/SYSTEM.md)" --enter --json >/dev/null || true
TASK_CODEX_IMPLEMENTER=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Codex-Implementer" --json | jq -r .id)
"$ORCA_BIN" worktree create --name wt-codex --agent codex --json >/dev/null
"$ORCA_BIN" orchestration worker-start --task "$TASK_CODEX_IMPLEMENTER" --worktree wt-codex --name Codex-Implementer --agent codex --json
"$ORCA_BIN" terminal send --text "$(cat agents/Codex-Implementer/SYSTEM.md)" --enter --json >/dev/null || true
"$ORCA_BIN" orchestration check --wait --types worker_done,escalation,question --timeout-ms 900000 --json

# --- Cross-critique (judge) via orca-cli worktrees + orchestration workers ---
TASK_CLAUDE_JUDGE=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Claude-Judge" --json | jq -r .id)
"$ORCA_BIN" worktree create --name wt-judge-claude --agent claude --json >/dev/null
"$ORCA_BIN" orchestration worker-start --task "$TASK_CLAUDE_JUDGE" --worktree wt-judge-claude --name Claude-Judge --agent claude --json
"$ORCA_BIN" terminal send --text "$(cat agents/Claude-Judge/SYSTEM.md)" --enter --json >/dev/null || true
TASK_GROK_JUDGE=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Grok-Judge" --json | jq -r .id)
"$ORCA_BIN" worktree create --name wt-judge-grok --agent grok --json >/dev/null
"$ORCA_BIN" orchestration worker-start --task "$TASK_GROK_JUDGE" --worktree wt-judge-grok --name Grok-Judge --agent grok --json
"$ORCA_BIN" terminal send --text "$(cat agents/Grok-Judge/SYSTEM.md)" --enter --json >/dev/null || true
TASK_CODEX_JUDGE=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Codex-Judge" --json | jq -r .id)
"$ORCA_BIN" worktree create --name wt-judge-codex --agent codex --json >/dev/null
"$ORCA_BIN" orchestration worker-start --task "$TASK_CODEX_JUDGE" --worktree wt-judge-codex --name Codex-Judge --agent codex --json
"$ORCA_BIN" terminal send --text "$(cat agents/Codex-Judge/SYSTEM.md)" --enter --json >/dev/null || true
"$ORCA_BIN" orchestration check --wait --types worker_done,escalation,question --timeout-ms 900000 --json

# --- Mediate and steal (mediate) via orchestration ---
TASK_GROK_MEDIATOR=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Grok-Mediator" --json | jq -r .id)
"$ORCA_BIN" orchestration worker-start --task "$TASK_GROK_MEDIATOR" --worktree current --name Grok-Mediator --agent grok --json
"$ORCA_BIN" terminal send --text "$(cat agents/Grok-Mediator/SYSTEM.md)" --enter --json >/dev/null || true
"$ORCA_BIN" orchestration check --wait --types worker_done --timeout-ms 900000 --json

# --- Final spec review (spec-review) via orchestration ---
TASK_FINAL_SPEC_REVIEWER=$("$ORCA_BIN" orchestration task-create --spec "$OBJECTIVE" --task-title "Final-Spec-Reviewer" --json | jq -r .id)
"$ORCA_BIN" orchestration worker-start --task "$TASK_FINAL_SPEC_REVIEWER" --worktree current --name Final-Spec-Reviewer --agent claude --json
"$ORCA_BIN" terminal send --text "$(cat agents/Final-Spec-Reviewer/SYSTEM.md)" --enter --json >/dev/null || true
"$ORCA_BIN" orchestration check --wait --types worker_done --timeout-ms 900000 --json

# HumanGate: merge-gate (orchestration)
"$ORCA_BIN" orchestration gate-create --task "$RUN_ID" --question "Create the PR from the winning worktree and merge to main?" --options '["merge", "hold"]' --json
echo "orca-ager run complete: $RUN_ID"
